# Generated by Django 6.0.3 on 2026-04-01 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cuenta_destino',
            field=models.ForeignKey(blank=True, help_text='Obligatorio solo para transferencias.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='wallet.cuenta'),
        ),
    ]
